project:
  type: website
  output-dir: docs

website:
  title: "Introduction to mapping and spatial analysis with R"
  navbar:
    left:
    - text: "Home"
      file: index.qmd
    - text: "Data"
      file: data.qmd
    - text: "Sessions"
      menu:
      - text: "Introduction"
        file: intro.qmd
      - text: "Spatial data"
        file: spatial_data.qmd
      - text: "Mapping with ggplot - part 1"
        file: ggplot1.qmd
      - text: "Simple features"
        file: sf.qmd
      - text: "Coordinate reference systems"
        file: crs.qmd   
      - text: "Mapping with ggplot - part 2"
        file: ggplot2.qmd
      - text: "Working with geometries in sf objects"
        file: geometric.qmd
      - text: "Spatial operations"
        file: spatial_ops.qmd
      - text: "Rasters"
        file: rasters.qmd
      - text: "Reading and writing spatial data"
        file: input_output.qmd
      - text: "R and QGIS"
        file: qgis.qmd
      - text: "Interactive maps"
        file: interactive.qmd
      - text: "Interpolation"
        file: interpolation.qmd
    - icon: github
      href: https://github.com/jmburgos/TCMSAR26

execute:
  message: false
  warning: false

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc-depth: 3
    message: false
    warning: false
    echo: true
    code-fold: false
